ExchangeBook/Models/BookType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ExchangeBook.Models
{
    public class BookType
    {
        [Key]
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public ICollection<MyBook> MyBooks { get; set; }
    }
}

ExchangeBook/Controllers/BookController.cs
using ExchangeBook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Http;
using java.nio.file;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;

namespace ExchangeBook.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        Context db = new Context();
        private IHostingEnvironment hostingEnv;

        public BookController(IHostingEnvironment env)

        {

            this.hostingEnv = env;

        }


        private static Random random = new Random();
        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }
        public IActionResult AddBook(int id)
        {

            List<SelectListItem> values = (from x in db.BookTypes.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.TypeName,
                                               Value = x.TypeId.ToString()
                                           }).ToList();
            ViewBag.values = values;
            ViewBag.Id = id;
            return View();
        }
        [HttpPost]
        public IActionResult AddBook(int id, MyBook book, UploadModel upload)
        {
            String random = RandomString(10);
            var FileDic = "Files";

            string FilePath = System.IO.Path.Combine(hostingEnv.WebRootPath, FileDic);

            if (!Directory.Exists(FilePath))

                Directory.CreateDirectory(FilePath);

            var fileName =random+upload.File.FileName;
           
            var filePath = System.IO.Path.Combine(FilePath, fileName);



            using (FileStream fs = System.IO.File.Create(filePath))

            {

                upload.File.CopyTo(fs);

            }




            if (!ModelState.IsValid)
            {
                return Redirect("~/Book/AddBook/" + id);
            }
            book.BookImage = "~/Files/"+fileName;
            book.UserId = id;
            ViewBag.Id = id;

            db.MyBooks.Add(book);
            db.SaveChanges();
            //if (file != null && file.ContentLength > 0)
            //    try
            //    {
            //        String random = RandomString(10);
            //       string path = Path.Combine(Server.MapPath("~/Upload/"),
            //        Path.GetFileName(random + ".mp4"));
            //        file.SaveAs(path);
            //        book.BookImage = "~/Upload/" + random + ".mp4";
            //        ViewBag.Message = "File uploaded successfully";
            //    }
            //    catch (Exception ex)
            //    {
            //        ViewBag.Message = "ERROR:" + ex.Message.ToString();
            //    }
            //else
            //{
            //    ViewBag.Message = "You have not specified a file.";
            //}
            return Redirect("~/Home/Profile/" + id);
        }
        public IActionResult Details(int id, int bookId, int person)
        {
            ViewBag.Id = id;
            
            MyBook detail = db.MyBooks.Where(x => x.BookId == bookId && x.UserId == person).SingleOrDefault();
            ViewBag.detail = detail;
            return View();
        }
    }
}

ExchangeBook/Views/Book/AddBook.cshtml
@{
    Layout = null;
    List<MyBook> bookList = ViewBag.BookList;
    int id = ViewBag.Id;
    var values = ViewBag.values;
    @model ExchangeBook.Models.MyBook;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Değiş tokuş</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="~/adsiter/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="~/adsiter/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/adsiter/css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="~/adsiter/images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="~/adsiter/css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="~/adsiter/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/adsiter/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">

</head>
<body>
    <!-- header section start -->
    <div class="header_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-lg-2">
                    <div class="logo"><a href="index.html"><img width="100px" src="~/adsiter/images/logo.png"></a></div>
                </div>
                <div class="col-sm-4 col-lg-7 ">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                            <div class="navbar-nav">
                                <a class="nav-item nav-link" href="/Home/Index/@id">Anasayfa</a>
                                <a class="nav-item nav-link" href="/Home/Profile/@id">Profilim</a>
                                <a class="nav-item nav-link" href="/Home/MyFav/@id">Favorilerim</a>
                                <a class="nav-item nav-link" href="/Home/Information/@id">Hakkımızda</a>
                                <a class="nav-item nav-link" href="/Message/MyMessage/@id"><img width="30px" src="~/adsiter/images/letter.png" /> </a>

                                <a class="nav-item nav-link" href="/Login/LogOut/"><img width="25px" src="~/adsiter/images/close.png" /></a>
                            </div>
                        </div>
                    </nav>
                </div>

                <div class="col-sm-5 col-lg-3">
                    <div class="search_main">
                        <button class="submit_bt"><a href="/Home/GiveYourOpinion/@id">Görüşlerini bildir</a></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- header section end -->

    <div class="contact_section layout_padding">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-9">
                    <div class="input_main ">
                        <div class="container validate-form">
                            @using (Html.BeginForm("AddBook", "Book", FormMethod.Post, new { enctype = "multipart/form-data", @id = id }))
                            {
                                <div class="form-group validate-input" data-validate="Parola Girin">
                                    @Html.TextBoxFor(m => m.BookName, new { placeholder = "Kitap Adı", @class = "email-bt" })
                                    @Html.ValidationMessageFor(m => m.BookName, "", new { @style = "color:red" })
                                </div>
                                <div class="form-group validate-input" data-validate="Parola Girin">
                                    @Html.TextBoxFor(m => m.BookAuthor, new { placeholder = "Yazar", @class = "email-bt" })
                                    @Html.ValidationMessageFor(m => m.BookAuthor, "", new { @style = "color:red" })

                                </div>

                                <div class="form-group">
                                    @Html.TextAreaFor(m => m.BookExplanation, new { @class = "massage-bt", placeholder = "Açıklama" })

                                </div>
                           
                                <br />
                                <div class="form-group">
                                    <input type="file" id="File_Upload" name="File" />
                                </div>
                                <button type="submit" class="submit_textMessageInput">Kitap Ekle</button>}

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- contact section end -->
    <!-- footer section start -->
    <div class="layout_padding footer_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-3">
                    <div><img src="~/adsiter/images/footer-logo.png"></div>
                    <p class="dolor_text">dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et sdolor sit amet,</p>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                    <h1 class="quick_text">Quick links</h1>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">Join Us</span></div>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">Maintenance</span></div>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">Language Packs</span></div>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">LearnPress</span></div>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">Release Status</span></div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                    <h1 class="subscribe_text">Subcribe email</h1>
                    <p class="ipsum_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit,</p>
                    <input type="text" class="email_text" placeholder="Your Email" name="Name">
                    <button class="submit_text">Submit</button>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                    <h1 class="quick_text">Contact Us</h1>
                    <div class="map_flag"><img src="images/map-flag.png"><span class="padding-left">London 145 United Kingdom</span></div>
                    <div class="dolor_text"><img src="images/email-icon.png"><span class="padding-left">adsiter@gmail.com</span></div>
                    <div class="dolor_text"><img src="images/phone-icon.png"><span class="padding-left">+12586954775</span></div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer section end -->
    <!-- copyright section start -->
    <div class="copyright">
        <p class="copyright_text">2019 All Rights Reserved. Design By <a href="https://html.design"> Free Html Templates</p>
    </div>
    <!-- copyright section end -->
    <!-- Javascript files-->
    <script src="~/adsiter/js/jquery.min.js"></script>
    <script src="~/adsiter/js/popper.min.js"></script>
    <script src="~/adsiter/js/bootstrap.bundle.min.js"></script>
    <script src="~/adsiter/js/jquery-3.0.0.min.js"></script>
    <script src="~/adsiter/js/plugin.js"></script>
    <!-- sidebar -->
    <script src="~/adsiter/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/adsiter/js/custom.js"></script>
    <!-- javascript -->
    <script src="~/adsiter/js/owl.carousel.js"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });

            $(".zoom").hover(function () {

                $(this).addClass('transition');
            }, function () {

                $(this).removeClass('transition');
            });
        });

    </script>

</body>
</html>

ExchangeBook/Views/Book/Details.cshtml
@{
    Layout = null;
    MyBook bookDetail = ViewBag.detail;
    int id = ViewBag.Id;
}   
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Değiş tokuş</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="~/adsiter/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="~/adsiter/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/adsiter/css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="~/adsiter/images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="~/adsiter/css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="~/adsiter/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/adsiter/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <script src="~/js/modernizer.js"></script>
    <script src="~/Scripts/jquery-3.4.1.slim.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <!-- header section start -->
    <div class="header_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-lg-2">
                    <div class="logo"><a href="index.html"><img width="100px" src="~/adsiter/images/logo.png"></a></div>
                </div>
                <div class="col-sm-4 col-lg-7 ">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                            <div class="navbar-nav">
                                <a class="nav-item nav-link" href="/Home/Index/@id">Anasayfa</a>
                                <a class="nav-item nav-link" href="/Home/Profile/@id">Profilim</a>
                                <a class="nav-item nav-link" href="/Home/MyFav/@id">Favorilerim</a>
                                <a class="nav-item nav-link" href="/Home/Information/@id">Hakkımızda</a>
                                <a class="nav-item nav-link" href="/Message/MyMessage/@id"><img width="30px" src="~/adsiter/images/letter.png" /> </a>

                                <a class="nav-item nav-link" href="/Login/LogOut/"><img width="25px" src="~/adsiter/images/close.png" /></a>
                            </div>
                        </div>
                    </nav>
                </div>

                <div class="col-sm-5 col-lg-3">
                    <div class="search_main">
                        <button class="submit_bt"><a href="/Home/GiveYourOpinion/@id">Görüşlerini bildir</a></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- header section end -->
    <!-- section PROMOTED start -->
    <div class=" layout_padding promoted_sectipon">
        <div class="container">
            <h1 class="promoted_text"><span style="border-bottom: 5px solid saddlebrown;">Kitabın detayları</span></h1>
            <div class="images_main">
                <div class="row">



                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="images"><img width="500px" height="325px" src=Url.Content(bookDetail.BookImage) style="width: 100%;"></div>
                        <div class="numbar_text"><span class="like-icon">@bookDetail.BookName</span></div>
                        <div class="numbar_text"><span class="like-icon">@bookDetail.BookAuthor</span></div>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        @if (bookDetail.BookExplanation != null)
                        {
                            <div class="numbar_text"><span class="like-icon">@bookDetail.BookExplanation</span></div>
                        }
                        else
                        { <div class="numbar_text"><span class="like-icon">Herhangi bir açıklama girilmemiş</span></div> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
                        }
                        <button class="mobile_bt"><a href="/Message/WriteMessage/?id=@id&userId=@bookDetail.UserId">Mesaj At</a></button><br />
                        <button class="mobile_bt"><a href="/Home/UserProfile/?id=@id&userId=@bookDetail.UserId">Diğer kitapları gör</a></button>
                    </div>



                    </div>
                </div>
        </div>
    </div>
    <!-- section PROMOTED end -->
    <!-- about section start -->
    <div class="layout_padding about_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1 class="about_taital">About Our Classified ads</h1>
                    <p class="lorem_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to</p>
                </div>
            </div>
        </div>
    </div>

    <!-- footer section start -->
    <div class="layout_padding footer_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-3">
                    <div><img src="~/adsiter/images/footer-logo.png"></div>
                    <p class="dolor_text">dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et sdolor sit amet,</p>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                    <h1 class="quick_text">Quick links</h1>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">Join Us</span></div>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">Maintenance</span></div>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">Language Packs</span></div>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">LearnPress</span></div>
                    <div class="chevron_arrow"><img src="images/chevron-arrow.png"><span class="padding-left">Release Status</span></div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                    <h1 class="subscribe_text">Subcribe email</h1>
                    <p class="ipsum_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit,</p>
                    <input type="text" class="email_text" placeholder="Your Email" name="Name">
                    <button class="submit_text">Submit</button>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3">
                    <h1 class="quick_text">Contact Us</h1>
                    <div class="map_flag"><img src="images/map-flag.png"><span class="padding-left">London 145 United Kingdom</span></div>
                    <div class="dolor_text"><img src="images/email-icon.png"><span class="padding-left">adsiter@gmail.com</span></div>
                    <div class="dolor_text"><img src="images/phone-icon.png"><span class="padding-left">+12586954775</span></div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer section end -->
    <!-- copyright section start -->
    <div class="copyright">
        <p class="copyright_text">2021 Tüm Hakları Saklıdır.</p>
    </div>
    <!-- copyright section end -->
    <!-- Javascript files-->
    <script src="~/adsiter/js/jquery.min.js"></script>
    <script src="~/adsiter/js/popper.min.js"></script>
    <script src="~/adsiter/js/bootstrap.bundle.min.js"></script>
    <script src="~/adsiter/js/jquery-3.0.0.min.js"></script>
    <script src="~/adsiter/js/plugin.js"></script>
    <!-- sidebar -->
    <script src="~/adsiter/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/adsiter/js/custom.js"></script>
    <!-- javascript -->
    <script src="~/adsiter/js/owl.carousel.js"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });

            $(".zoom").hover(function () {

                $(this).addClass('transition');
            }, function () {

                $(this).removeClass('transition');
            });
        });

    </script>

</body>
</html>